/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import java.awt.Color;
import javax.swing.JOptionPane;

/**
 *
 * @author Laboratorio-Info
 */
public class Inicio_GUI extends javax.swing.JFrame {

    /**
     * Creates new form Inicio_GUI
     */
    public Inicio_GUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        valor1_txt = new javax.swing.JTextField();
        valor2_txt = new javax.swing.JTextField();
        soma_BTN = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        resp_txt = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        resp2_txt = new javax.swing.JLabel();
        limpar_BTN = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel2.setBackground(new java.awt.Color(204, 204, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Calculadora da Kim", 0, 0, new java.awt.Font("Tahoma", 2, 12), new java.awt.Color(255, 255, 255))); // NOI18N
        jPanel2.setLayout(null);

        jLabel3.setText("Valor 1");
        jPanel2.add(jLabel3);
        jLabel3.setBounds(170, 20, 50, 14);

        jLabel4.setText("Valor 2");
        jPanel2.add(jLabel4);
        jLabel4.setBounds(170, 90, 40, 14);
        jPanel2.add(valor1_txt);
        valor1_txt.setBounds(160, 50, 40, 20);
        jPanel2.add(valor2_txt);
        valor2_txt.setBounds(160, 120, 40, 20);

        soma_BTN.setText("+");
        soma_BTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                soma_BTNActionPerformed(evt);
            }
        });
        jPanel2.add(soma_BTN);
        soma_BTN.setBounds(120, 230, 50, 23);

        jLabel1.setText("Resultado");
        jPanel2.add(jLabel1);
        jLabel1.setBounds(110, 160, 60, 14);
        jPanel2.add(resp_txt);
        resp_txt.setBounds(110, 180, 50, 20);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/garf.gif"))); // NOI18N
        jPanel2.add(jLabel2);
        jLabel2.setBounds(20, 230, 320, 71);
        jPanel2.add(resp2_txt);
        resp2_txt.setBounds(190, 184, 34, 20);

        limpar_BTN.setText("Limpar");
        limpar_BTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                limpar_BTNActionPerformed(evt);
            }
        });
        jPanel2.add(limpar_BTN);
        limpar_BTN.setBounds(290, 120, 63, 23);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setSize(new java.awt.Dimension(400, 300));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void soma_BTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_soma_BTNActionPerformed
       double v1 = Double.parseDouble(valor1_txt.getText());
       double v2 = Double.parseDouble(valor2_txt.getText());
       double resp = v1 + v2;
       //JOptionPane.showMessageDialog(null,"O resultado é: " + resp);
       resp_txt.setText(String.valueOf(resp));
       resp_txt.setBackground(Color.blue);
       resp2_txt.setText(String.valueOf(resp));
       resp2_txt.setBackground(Color.red);
    }//GEN-LAST:event_soma_BTNActionPerformed

    private void limpar_BTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_limpar_BTNActionPerformed
        valor1_txt.setText("");
        valor2_txt.setText("");
        resp_txt.setText("");
        resp2_txt.setText("");
        resp_txt.setBackground(Color.white);
        resp2_txt.setBackground(Color.white);
    }//GEN-LAST:event_limpar_BTNActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Inicio_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Inicio_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Inicio_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Inicio_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Inicio_GUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JButton limpar_BTN;
    private javax.swing.JLabel resp2_txt;
    private javax.swing.JTextField resp_txt;
    private javax.swing.JButton soma_BTN;
    private javax.swing.JTextField valor1_txt;
    private javax.swing.JTextField valor2_txt;
    // End of variables declaration//GEN-END:variables
}
